version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      HOST: 0.0.0.0
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
