version: '3.8'

networks:
  nuxt:
    name: nuxt

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: nuxt:local
    networks:
      - nuxt
    ports:
      - "3000:80"
    environment:
      HOST: 0.0.0.0
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
  storybook:
    depends_on:
      - web
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nuxt
    ports:
      - "3003:81"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
